### ISSUE TITLE
[Feature Request] Replace CSS variables with variable's value when targeting IE

### ISSUE THREAD

**Issue by DannyJJK** [parcel-bundler/parcel-css#159] opened 2022-04-16 21:40 UTC
Internet Explorer doesn't have support for CSS variables, but since Parcel CSS doesn't work on SCSS files, it'd be nice to have a way to support CSS variables and have it convert them when targeting Internet Explorer

**Comment by devongovett** [comment] 2022-04-17 18:49
Duplicate of #69. This isn't really possible without knowing the DOM structure.

**Closed by devongovett** 2022-04-17 18:49 UTC
